# -*- coding: utf-8 -*-
"""Baseline_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V-qsnezgHnQhzSUGwJGjKN6JDS5y6tHM
"""

"""
STEP 1: Prepare DDXPlus Training Data
Convert evidence codes to human-readable training examples
"""

from datasets import load_dataset
from huggingface_hub import hf_hub_download
import json
from tqdm import tqdm
import pandas as pd

print("="*70)
print("STEP 1: PREPARE DDXPLUS TRAINING DATA")
print("="*70)


print("\n[1/6] Loading DDXPlus dataset...")
ddxplus = load_dataset("aai530-group6/ddxplus")

print(f"✓ Train: {len(ddxplus['train']):,} cases")
print(f"✓ Validation: {len(ddxplus['validate']):,} cases")
print(f"✓ Test: {len(ddxplus['test']):,} cases")


print("\n[2/6] Loading evidence and condition mappings...")

repo_id = "aai530-group6/ddxplus"

# Download evidence mapping
evidence_file = hf_hub_download(
    repo_id=repo_id,
    filename="release_evidences.json",
    repo_type="dataset"
)

with open(evidence_file, 'r') as f:
    evidence_map = json.load(f)

print(f"✓ Evidence codes: {len(evidence_map)}")

# Download condition mapping
condition_file = hf_hub_download(
    repo_id=repo_id,
    filename="release_conditions.json",
    repo_type="dataset"
)

with open(condition_file, 'r') as f:
    condition_map = json.load(f)

print(f"✓ Conditions: {len(condition_map)}")


def decode_evidence_to_text(evidence_code, evidence_map):
    """Convert evidence code to readable symptom"""
    if evidence_code in evidence_map:
        ev_data = evidence_map[evidence_code]
        return ev_data.get('question_en', evidence_code)
    return evidence_code

def parse_evidences_string(evidences_str):
    """Parse the EVIDENCES field - it's a string representation of a list"""
    try:
        # Remove brackets and quotes, then split
        if isinstance(evidences_str, str):
            # Use ast.literal_eval for safe parsing of Python list string
            import ast
            return ast.literal_eval(evidences_str)
        return evidences_str if isinstance(evidences_str, list) else []
    except:
        return []

def decode_evidence_with_value(evidence_code, evidence_map):
    """
    Decode evidence that may include a value
    Format: 'E_55_@_V_89' means evidence E_55 with value V_89
    """
    # Check if evidence has a value attached
    if '_@_' in evidence_code:
        parts = evidence_code.split('_@_')
        ev_code = parts[0]  # e.g., E_55
        value_code = parts[1] if len(parts) > 1 else None  # e.g., V_89
    else:
        ev_code = evidence_code
        value_code = None

    # Get the evidence question
    if ev_code not in evidence_map:
        return evidence_code

    ev_data = evidence_map[ev_code]
    question = ev_data.get('question_en', ev_code)

    # If it's a binary question (just yes/no)
    if ev_data.get('data_type') == 'B' and value_code is None:
        # Simplify to a statement
        statement = question.replace("Do you have ", "has ")
        statement = statement.replace("Have you ", "has ")
        statement = statement.replace("Are you ", "is ")
        statement = statement.replace("Did you ", "")
        statement = statement.replace("?", "")
        return statement.strip()

    # If it has a value, decode that too
    if value_code and 'value_meaning' in ev_data:
        value_meanings = ev_data.get('value_meaning', {})
        if value_code in value_meanings:
            value_text = value_meanings[value_code].get('en', value_code)
            # Create meaningful statement
            base_question = question.replace("?", "").strip()
            return f"{base_question}: {value_text}"

    # Default: return simplified question
    return question.replace("?", "").strip()

def create_symptom_description(evidences_list, evidence_map, max_symptoms=10):
    """
    Create natural language symptom description
    """
    symptoms = []

    for ev_code in evidences_list[:max_symptoms]:
        symptom_text = decode_evidence_with_value(ev_code, evidence_map)

        # Clean up and add
        if symptom_text and len(symptom_text) > 3:
            symptoms.append(symptom_text)

    if len(symptoms) == 0:
        return "multiple symptoms reported"

    symptom_str = "; ".join(symptoms)

    if len(evidences_list) > max_symptoms:
        symptom_str += f"; plus {len(evidences_list) - max_symptoms} additional findings"

    return symptom_str


def format_case_for_training(case, evidence_map):
    """
    Convert DDXPlus case to LLM training format

    Format for Phase 2 (Standard): Just symptoms → diagnosis
    Format for Phase 3 (Contextual): Cognitive prompt + symptoms → diagnosis
    """
    # Parse evidences
    evidences_list = parse_evidences_string(case['EVIDENCES'])

    # Create symptom description
    symptoms_text = create_symptom_description(evidences_list, evidence_map)

    # Patient info
    age = case['AGE']
    sex = "Male" if case['SEX'] == 'M' else "Female"

    # Standard format (Phase 2)
    standard_format = {
        "instruction": "Based on the patient symptoms, provide the diagnosis.",
        "input": f"Patient: {age}-year-old {sex}\nSymptoms: {symptoms_text}",
        "output": case['PATHOLOGY']
    }

    # Contextual format (Phase 3)
    contextual_prompts = [
        "Think about how these symptoms connect to known disease patterns. Consider the patient's age and sex.",
        "Analyze the symptom cluster and connect it to underlying disease mechanisms.",
        "Consider differential diagnoses and identify the most likely condition based on the symptom pattern.",
        "Reflect on how these clinical findings relate to common disease presentations."
    ]

    # Choose prompt based on case index for variety
    prompt_idx = hash(case['PATHOLOGY']) % len(contextual_prompts)
    contextual_prompt = contextual_prompts[prompt_idx]

    contextual_format = {
        "instruction": f"{contextual_prompt}\n\nBased on the patient symptoms, provide the diagnosis.",
        "input": f"Patient: {age}-year-old {sex}\nSymptoms: {symptoms_text}",
        "output": case['PATHOLOGY']
    }

    return standard_format, contextual_format



print("\n[3/6] Processing training data...")

# Process sample first (1000 cases for testing)
sample_size = 1000  # Change to len(ddxplus['train']) for full dataset
print(f"Processing {sample_size:,} cases (change sample_size for more)...")

standard_examples = []
contextual_examples = []

for i in tqdm(range(min(sample_size, len(ddxplus['train']))), desc="Converting"):
    case = ddxplus['train'][i]

    try:
        standard, contextual = format_case_for_training(case, evidence_map)
        standard_examples.append(standard)
        contextual_examples.append(contextual)
    except Exception as e:
        continue

print(f"\n✓ Converted {len(standard_examples):,} cases")


print("\n[4/6] Saving training data...")

# Phase 2: Standard fine-tuning format
with open('ddxplus_phase2_training.jsonl', 'w') as f:
    for ex in standard_examples:
        f.write(json.dumps(ex) + '\n')

print(f"✓ Saved: ddxplus_phase2_training.jsonl ({len(standard_examples):,} examples)")

# Phase 3: Contextual fine-tuning format
with open('ddxplus_phase3_training.jsonl', 'w') as f:
    for ex in contextual_examples:
        f.write(json.dumps(ex) + '\n')

print(f"✓ Saved: ddxplus_phase3_training.jsonl ({len(contextual_examples):,} examples)")

# Also save as JSON for inspection
with open('ddxplus_training_sample.json', 'w') as f:
    json.dump({
        'standard': standard_examples[:10],
        'contextual': contextual_examples[:10]
    }, f, indent=2)

print(f"✓ Saved: ddxplus_training_sample.json (10 examples for inspection)")


print("\n[5/6] Sample training examples...")

print("\n" + "="*70)
print("PHASE 2 FORMAT (Standard Fine-tuning)")
print("="*70)

ex = standard_examples[0]
print(f"\n📝 Instruction:\n{ex['instruction']}")
print(f"\n📋 Input:\n{ex['input']}")
print(f"\n✅ Output:\n{ex['output']}")

print("\n" + "="*70)
print("PHASE 3 FORMAT (Contextual Fine-tuning)")
print("="*70)

ex = contextual_examples[0]
print(f"\n🧠 Instruction:\n{ex['instruction']}")
print(f"\n📋 Input:\n{ex['input']}")
print(f"\n✅ Output:\n{ex['output']}")


print("\n[6/6] Analyzing disease distribution...")

diseases = [ex['output'] for ex in standard_examples]
disease_counts = pd.Series(diseases).value_counts()

print(f"\nTop 10 diseases in training sample:")
for i, (disease, count) in enumerate(disease_counts.head(10).items(), 1):
    print(f"  {i:2d}. {disease}: {count} cases ({count/len(diseases)*100:.1f}%)")


print("\n" + "="*70)
print("STEP 1 COMPLETE!")
print("="*70)

"""
STEP 2: Phase 1 Baseline Evaluation (Simplified)
Just test the base Llama model - no training yet
"""

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from datasets import load_dataset
from huggingface_hub import hf_hub_download
import json
import ast
from tqdm import tqdm

print("="*70)
print("STEP 2: PHASE 1 BASELINE EVALUATION")
print("="*70)



print("\n[1/5] Loading base Llama model (no training)...")
print("This will download ~6GB if first time...\n")

MODEL_NAME = "meta-llama/Llama-3.2-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    device_map="auto"
)
model.eval()

print("✓ Base model loaded (this is Meta's pre-trained model)")
print("✓ No medical fine-tuning yet - this is the baseline")



print("\n[2/5] Loading DDXPlus test set...")

ddxplus = load_dataset("aai530-group6/ddxplus")
test_data = ddxplus['test']

print(f"✓ Test set: {len(test_data):,} cases")
print(f"✓ We'll test on 10 cases for demonstration")



print("\n[3/5] Loading evidence decoder...")

repo_id = "aai530-group6/ddxplus"
evidence_file = hf_hub_download(repo_id, "release_evidences.json", repo_type="dataset")

with open(evidence_file, 'r') as f:
    evidence_map = json.load(f)

print(f"✓ Loaded {len(evidence_map)} evidence codes")



def decode_symptoms(case, evidence_map):
    """
    Convert evidence codes to readable text - IMPROVED VERSION
    """
    # Parse evidences (it's a string that looks like a list)
    evidences_str = case['EVIDENCES']
    evidences_list = ast.literal_eval(evidences_str)

    symptoms = []

    # Decode each evidence
    for ev_code in evidences_list[:12]:  # First 12 symptoms
        # Handle evidence@value format
        if '_@_' in ev_code:
            parts = ev_code.split('_@_')
            base_code = parts[0]
            value_code = parts[1] if len(parts) > 1 else None
        else:
            base_code = ev_code
            value_code = None

        # Skip if not in map
        if base_code not in evidence_map:
            continue

        ev_data = evidence_map[base_code]
        question = ev_data.get('question_en', '')

        if not question:
            continue

        # For binary questions (yes/no)
        if ev_data.get('data_type') == 'B':
            # Convert question to statement
            symptom = question.lower()
            symptom = symptom.replace('do you have ', '')
            symptom = symptom.replace('have you ', '')
            symptom = symptom.replace('are you ', '')
            symptom = symptom.replace('did you ', '')
            symptom = symptom.replace('?', '')
            symptom = symptom.strip()

            if len(symptom) > 5:  # Only add meaningful symptoms
                symptoms.append(symptom)

        # For questions with values
        elif value_code and 'value_meaning' in ev_data:
            value_meanings = ev_data.get('value_meaning', {})
            if value_code in value_meanings:
                value_text = value_meanings[value_code].get('en', '')
                if value_text and value_text != 'N' and value_text != 'NA':
                    # Extract key part of question
                    q_short = question.split('?')[0].lower()
                    q_short = q_short.replace('do you ', '').replace('have you ', '')
                    symptoms.append(f"{q_short}: {value_text}")

    # Return formatted string
    if len(symptoms) == 0:
        return "patient presents with medical complaint"

    return ", ".join(symptoms)


print("\n[4/5] Testing base model on 10 cases...")
print("(This shows you what Phase 1 baseline looks like)\n")

results = []

for i in tqdm(range(10), desc="Evaluating"):
    case = test_data[i]

    # Decode symptoms
    symptoms = decode_symptoms(case, evidence_map)
    true_diagnosis = case['PATHOLOGY']

    # Create prompt
    sex_text = "Male" if case['SEX'] == 'M' else "Female"
    prompt = f"""Based on these patient symptoms, what is the most likely diagnosis?

Patient: {case['AGE']}-year-old {sex_text}
Symptoms: {symptoms}

Provide only the disease name.
Diagnosis:"""

    # Get model prediction
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=20,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    # Decode prediction
    # outputs is already the token IDs tensor
    generated_ids = outputs[0][inputs.input_ids.shape[-1]:]
    prediction = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()

    # Clean up prediction - extract just the disease name
    # Remove any explanatory text after newline or period
    #prediction = prediction.split('\n')[0].strip()
    #prediction = prediction.split('.')[0].strip()

    # Remove common prefixes
    #prediction = prediction.replace('Diagnosis:', '').strip()
    #prediction = prediction.replace('The diagnosis is', '').strip()

    # Check if correct (fuzzy matching)
    is_correct = False

    # Exact match
    if prediction.lower() == true_diagnosis.lower():
        is_correct = True
    # Partial match (e.g., "Pneumothorax" in "Spontaneous pneumothorax")
    elif prediction.lower() in true_diagnosis.lower():
        is_correct = True
    elif true_diagnosis.lower() in prediction.lower():
        is_correct = True

    results.append({
        'case': i+1,
        'symptoms': symptoms[:80] + "...",
        'true_diagnosis': true_diagnosis,
        'predicted': prediction,
        'correct': '✓' if is_correct else '✗'
    })

    # Print each case
    print(f"\n{'─'*70}")
    print(f"Case {i+1}:")
    print(f"  Symptoms: {symptoms[:100]}...")
    print(f"  True Diagnosis: {true_diagnosis}")
    print(f"  Model Predicted: {prediction}")
    print(f"  Result: {'✅ CORRECT' if is_correct else '❌ WRONG'}")



print("\n[5/5] Calculating baseline accuracy...")

correct_count = sum(1 for r in results if r['correct'] == '✓')
total_count = len(results)
accuracy = (correct_count / total_count) * 100

print("\n" + "="*70)
print("PHASE 1 BASELINE RESULTS")
print("="*70)

print(f"\n📊 Results on {total_count} cases:")
print(f"   Correct: {correct_count}/{total_count}")
print(f"   Accuracy: {accuracy:.1f}%")

print(f"\n💭 What this means:")
if accuracy < 10:
    print(f"   The base model has almost no diagnostic ability")
    print(f"   This is expected - it wasn't trained on medical diagnosis")
elif accuracy < 30:
    print(f"   The base model has minimal diagnostic ability")
    print(f"   Slightly better than random guessing (~2% for 49 diseases)")
else:
    print(f"   The base model has some diagnostic ability from pre-training")
    print(f"   But still needs fine-tuning for good performance")

print(f"\n✨ Next Steps:")
print(f"   Phase 2: Fine-tune on DDXPlus training data")
print(f"   Expected improvement: 20-30% accuracy → 60-70%")

# Save results
import pandas as pd
df = pd.DataFrame(results)
df.to_csv('phase1_baseline_results.csv', index=False)
print(f"\n✓ Results saved to: phase1_baseline_results.csv")

print("\n" + "="*70)
print("✅ PHASE 1 COMPLETE!")
print("="*70)

from huggingface_hub import login

# You'll need a Hugging Face token
login()